-- ============================================
-- RUN THIS IN SUPABASE SQL EDITOR
-- Adds: Wordle table, difficulty column, Hard + Easy trivia questions
-- ============================================

-- Wordle games table
CREATE TABLE IF NOT EXISTS wordle_games (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  team_member_id TEXT REFERENCES team(id) NOT NULL,
  word TEXT NOT NULL,
  guesses TEXT[] DEFAULT '{}',
  solved BOOLEAN DEFAULT false,
  played_date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(team_member_id, played_date)
);

ALTER TABLE wordle_games ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own wordle games"
  ON wordle_games FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can insert wordle games"
  ON wordle_games FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Users can update own wordle games"
  ON wordle_games FOR UPDATE TO authenticated USING (true);

-- Add difficulty column to trivia
ALTER TABLE trivia_questions ADD COLUMN IF NOT EXISTS difficulty TEXT DEFAULT 'Easy';

-- Set existing questions to Medium
UPDATE trivia_questions SET difficulty = 'Medium' WHERE difficulty IS NULL OR difficulty = 'Easy';

-- HARD QUESTIONS
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('In what year did Joseph and Valerie Stote break ground on the original Domes building on Rt. 28?', '2014', '2016', '2020', '2024', 'B', 'The Stotes broke ground in 2016, paying homage to the geodesic ideal popularized by Fuller.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('Why did the geodesic dome appeal to Buckminster Fuller? (Pick the BEST answer.)', 'It was inexpensive to build', 'It was extremely strong, omnitriangulated, and enclosed the most volume for the least surface area', 'It looked impressive', 'It was easy to manufacture', 'B', 'Fuller loved that it was extremely strong despite its light weight, that the omnitriangulated surface was inherently stable, and that a sphere encloses the greatest volume for the least surface area.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('During which growth stage do cannabis plants need higher phosphorus and potassium?', 'Seedling stage', 'Vegetative stage', 'Flowering stage', 'All stages equally', 'C', 'Flowering stage. Vegetative needs more nitrogen for leaf and stem development. Flowering needs more P and K to support bud formation.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('Why must cultivators identify and cull male cannabis plants?', 'Males don''t produce flowers', 'Males pollinate females, reducing THC content', 'Males grow too tall', 'Males attract more pests', 'B', 'Only females produce THC flower, and more THC develops when the flower isn''t pollinated. Males get culled to keep females unpollinated.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('Why is the low boiling point of hydrocarbons (like butane) considered an advantage in extraction?', 'It makes the extract burn faster', 'It allows the solvent to be purged at temperatures that don''t destroy terpenes', 'It reduces extraction time', 'It produces more THC', 'B', 'Butane purges at 30.2 F. Terpenes start degrading at higher temperatures, so the low boiling point keeps the flavor profile intact.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('A customer says they want something that ''hits fast but lasts a while.'' Which product type best matches?', 'Edibles', 'Vape cart', 'Tincture', 'Topical', 'C', 'Tincture. Sublingual absorption gives 10-15 minute onset (fast like a vape), while the swallowed portion processes through the liver for up to 4 hours (long like an edible).', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('What''s the difference between a 510-thread cartridge and a pod system?', '510-thread is more potent', '510-thread is universal; pods are proprietary to specific brands', 'Pods are stronger', 'There is no difference', 'B', '510-thread is the industry standard, compatible with many batteries. Pods (like PAX Era) are proprietary, kind of like Keurig vs. drip coffee.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('What''s the typical THC content of shatter?', 'Around 30%', 'Around 60%', 'Around 90%', 'Around 99%', 'C', 'Shatter typically exceeds 90% THC. It''s one of the more potent concentrates.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('What are ''pistils'' on cannabis flower?', 'The reproductive organs (the tiny orange or white hairs)', 'The resin glands', 'The seeds', 'The stems', 'A', 'Pistils are the reproductive organs, appearing as tiny white-yellow hairs that turn orange as the plant matures.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('What''s the typical THC content of ''sauce'' compared to other concentrates?', 'Around 30%', 'Around 60%', 'Around 90%', 'Around 99%', 'B', 'Around 60%. Sauce is a high-terpene full-spectrum extract prized for flavor, not max potency.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('Which consumption method bypasses the digestive system AND the liver entirely?', 'Edibles', 'Tinctures (when fully swallowed)', 'Smoking/vaping', 'Capsules', 'C', 'Inhalation methods deliver cannabinoids straight to the bloodstream via the lungs. No digestive system, no liver first-pass effect.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('What makes capsules different from tinctures even though both are taken orally?', 'Capsules have higher THC content', 'Tinctures have sublingual absorption; capsules are purely digestive', 'Capsules are cheaper', 'Capsules contain CBD only', 'B', 'Tinctures held under the tongue absorb partially through mucous membranes for faster onset. Capsules go entirely through the digestive system.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('Which method is BEST suited for someone with respiratory issues who wants fast-acting relief?', 'Smoking flower', 'Dabbing concentrates', 'Sublingual tincture', 'Vape cart', 'C', 'Sublingual tincture. Fast onset (10-15 minutes) without any inhalation.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('Why should you wait at least 2 hours before consuming more edibles?', 'It''s the law', 'Effects can take 30 minutes to 2 hours to manifest, so you risk overconsumption', 'Your stomach needs to settle', 'The taste fades', 'B', 'Because the onset is so delayed, customers often think it''s not working and take more. Then both doses hit at once.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('Why might cannabis affect someone differently depending on their ''set and setting''?', 'It doesn''t actually', 'Psychological state and environment influence the cannabis experience', 'Set and setting only affects edibles', 'Only experienced users care about this', 'B', 'Stress, mood, and surroundings affect perceived effects. Someone anxious in a chaotic environment may have a very different experience.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('Why is freezing cannabis flower generally NOT recommended?', 'It changes the flavor', 'It makes trichomes brittle, causing them to break off and reducing potency', 'It encourages mold', 'It''s illegal', 'B', 'Cold makes trichomes brittle and breakable. Since trichomes contain most of the cannabinoids and terpenes, breaking them off reduces potency.', 'cannabis', 'Hard');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('How should vape cartridges ideally be stored?', 'On their side, in direct sunlight', 'Upright, at room temperature, away from light, disconnected from battery', 'Refrigerated and laying flat', 'It doesn''t matter', 'B', 'Upright prevents leaks, room temperature (50-80 F), away from light (UV degrades THC), and disconnected from the battery.', 'cannabis', 'Hard');

-- EASY QUESTIONS
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('What was Joseph and Valerie Stote''s original dream for the Domes on Rt. 28?', 'A cannabis dispensary', 'A community hub with local organic plants and produce', 'An event venue', 'A music recording studio', 'B', 'Their dream was to create a community hub filled with local organic plants and produce for all to enjoy.', 'cannabis', 'Easy');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('What is hash made from?', 'Cannabis stems and leaves', 'Mechanically separated trichomes', 'Solvent-extracted oil', 'Fermented cannabis flower', 'B', 'Hash is one of the oldest concentrates, produced by mechanically separating trichomes from cannabis flower and pressing them.', 'cannabis', 'Easy');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('Which extraction method is solventless?', 'Hydrocarbon extraction', 'Ethanol extraction', 'Ice water hash (bubble hash)', 'Supercritical CO2 extraction', 'C', 'Ice water hash uses cold water and agitation to separate trichomes. No chemical solvents needed.', 'cannabis', 'Easy');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('What''s the maximum amount of THC allowed in a single package of edibles in New York?', '50mg', '100mg', '200mg', 'No limit', 'B', '100mg per package, typically broken into 5mg or 10mg servings. This is a NY regulation.', 'cannabis', 'Easy');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('What''s the legal purchase limit for THC flower per transaction in New York for adults 21+?', '1 ounce', '2 ounces', '3 ounces', '5 ounces', 'C', '3 ounces of flower, plus up to 24 grams of cannabis concentrates. Memorize this for customers.', 'cannabis', 'Easy');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('Which of the following is NOT a common consistency of cannabis concentrate?', 'Shatter', 'Crumble', 'Marshmallow', 'Budder', 'C', 'Shatter, crumble, budder, sauce, diamonds, rosin, live resin are all real consistencies. Marshmallow is not.', 'cannabis', 'Easy');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('How long does it typically take to feel the effects of an edible?', '5-10 minutes', '15-20 minutes', '30 minutes to 2 hours', '3-4 hours', 'C', '30 minutes to 2 hours. This is why ''start low and go slow'' is the rule with edibles.', 'cannabis', 'Easy');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('How fast does smoking or vaping typically take to produce effects?', 'Within minutes', '15-45 minutes', '1-2 hours', 'Several hours', 'A', 'Effects from inhalation methods are typically felt within minutes.', 'cannabis', 'Easy');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('Which consumption method has the longest-lasting effects (typically)?', 'Smoking', 'Vaping', 'Edibles', 'Dabbing', 'C', 'Edibles can last several hours because of the liver metabolism conversion to 11-hydroxy-THC.', 'cannabis', 'Easy');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('What''s the recommended starting dose of THC for someone new to edibles?', '1mg', '2.5 to 5mg', '10mg', '25mg', 'B', '2.5 to 5mg, with at least 2 hours before considering more.', 'cannabis', 'Easy');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('What''s the ideal humidity range for storing cannabis flower?', '25-35%', '45-55%', '55-65%', '70-80%', 'C', '55-65% relative humidity. Below: flower dries out. Above: mold risk.', 'cannabis', 'Easy');
INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty) VALUES ('Why does NY require child-resistant packaging on cannabis products?', 'It''s just a tradition', 'To prevent accidental ingestion by children', 'To keep products fresh', 'To make products look professional', 'B', 'Child-resistant packaging is required to prevent accidental ingestion by minors.', 'cannabis', 'Easy');
