-- STEP 1: Create brands table
CREATE TABLE IF NOT EXISTS brands (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  location TEXT,
  known_for TEXT,
  product_types TEXT,
  talking_points TEXT[],
  is_active BOOLEAN DEFAULT true,
  featured_week DATE,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE brands ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read for authenticated" ON brands
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow insert for authenticated" ON brands
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow update for authenticated" ON brands
  FOR UPDATE TO authenticated USING (true);

-- STEP 2: Seed all brands (names only for most, details for researched ones)
INSERT INTO brands (name, description, location, known_for, product_types, talking_points, is_active) VALUES
('1906', 'Cannabis brand combining THC with adaptogens and plant medicines in discreet pill form.', 'Multi-state', 'Effect-specific tablets (Sleep, Focus, Chill) with fast onset under 20 minutes', 'Tablets, Drops', ARRAY['Each product targets a specific feeling - like Sleep, Focus, or Chill','They use plant medicines alongside THC for enhanced effects','Onset is under 20 minutes - way faster than most edibles','Great for customers new to cannabis who want precise dosing'], true),
('1937', null, null, null, null, null, true),
('2 X Baked', null, null, null, null, null, true),
('5 Boro', null, null, null, null, null, true),
('ATC', null, null, null, null, null, true),
('Aeterna', null, null, null, null, null, true),
('Alchemy Pure', 'Small-batch, sun-grown cannabis with solventless extraction from 25+ years of organic farming.', 'Hudson Valley, NY', 'Solventless extraction and organic growing methods', 'Flower, Concentrates', ARRAY['Over 25 years of organic farming experience','They use solventless extraction - no chemicals, just heat and pressure','Small-batch means higher quality control','Local Hudson Valley brand - support local agriculture'], true),
('Alibi', null, null, null, null, null, true),
('All Day', null, null, null, null, null, true),
('All Night', null, null, null, null, null, true),
('All That Chocolate', null, null, null, null, null, true),
('Alpha Budz', null, null, null, null, null, true),
('Angry Bears', null, null, null, null, null, true),
('Animal House', 'Premium hand-grown flower from the Hudson Valley, known for kief-infused pre-rolls.', 'Hudson Valley, NY', 'Kief-infused pre-rolls and hand-grown premium flower', 'Flower, Pre-rolls', ARRAY['Their pre-rolls are infused with kief for extra potency','All flower is hand-grown in the Hudson Valley','Premium small-batch quality','Great option for customers looking for a stronger pre-roll experience'], true),
('Anthem', null, null, null, null, null, true),
('Aphrodite', 'Pre-rolls from Alchemy Farm in Pine Plains featuring a unique star-and-moon filter system.', 'Pine Plains, NY', 'Unique star-and-moon filter design on pre-rolls', 'Pre-rolls', ARRAY['Made at Alchemy Farm in Pine Plains, NY','Their signature star-and-moon filter system is unique in the market','Locally grown and crafted','Beautiful packaging makes it a great gift option'], true),
('Aster', null, null, null, null, null, true),
('Audrey Hempburn', null, null, null, null, null, true),
('Ayrloom', 'Cannabis brand from fifth-generation Beak & Skiff Apple Orchards with century-old agricultural heritage.', 'Syracuse/Upstate NY', 'Cannabis beverages with nano-emulsification technology', 'Beverages, Edibles', ARRAY['Comes from Beak & Skiff Apple Orchards - five generations of farming','They use nano-emulsification so effects kick in faster','Upstate NY heritage brand with deep agricultural roots','Great entry point for customers who prefer drinks over smoking'], true),
('B Noble', null, null, null, null, null, true),
('BIG FUN!', null, null, null, null, null, true),
('Bannermans Batch', null, null, null, null, null, true),
('Beboe', 'Luxury cannabis brand called "the Hermes of Marijuana," co-founded by tattoo artist Scott Campbell.', 'Multi-state (GTI)', 'Socially-dosed luxury vapes and pastilles', 'Vapes, Gummies, Pastilles', ARRAY['Known as the Hermes of Marijuana - luxury cannabis','Co-founded by famous tattoo artist Scott Campbell','Socially-dosed means lower THC per serving - perfect for beginners','Refined flavors and elegant packaging'], true),
('Birdies', null, null, null, null, null, true),
('Blak Mar', null, null, null, null, null, true),
('Blazy Susan', null, null, null, null, null, true),
('Blotter', null, null, null, null, null, true),
('Bonanza', null, null, null, null, null, true),
('Booty Shake', null, null, null, null, null, true),
('Brass Knuckles', null, null, null, null, null, true),
('Bronx B', null, null, null, null, null, true),
('Butter', null, null, null, null, null, true),
('Calamity Jane', null, null, null, null, null, true),
('Cali Honey', null, null, null, null, null, true),
('Camino', 'Cannabis gummies created by Kiva Confections with precisely dosed fruit flavors.', 'California', 'Precisely dosed THC gummies and sours', 'Gummies, Edibles', ARRAY['Made by Kiva Confections - one of the top edibles companies','Each gummy is precisely dosed for consistent experience','Multiple flavor and effect options','Great taste - customers often say they taste like regular candy'], true),
('Cannabis Leaf', null, null, null, null, null, true),
('Cannatela', null, null, null, null, null, true),
('Chef For Higher', null, null, null, null, null, true),
('Claybourne Co.', null, null, null, null, null, true),
('Collin Russell Glassworks', null, null, null, null, null, true),
('Continental Exotics', null, null, null, null, null, true),
('Cookies', 'Global cannabis lifestyle brand founded by Berner with 70+ proprietary cultivars.', 'San Francisco, CA', 'Premium genetics, lifestyle brand, 45+ retail locations', 'Flower, Pre-rolls, Vapes, Edibles', ARRAY['Founded by rapper Berner - massive cultural influence','Over 70 proprietary cannabis strains they developed','One of the most recognized cannabis brands globally','Their genetics are considered top-tier in the industry'], true),
('Curio Wellness', null, null, null, null, null, true),
('Cycling Frog', null, null, null, null, null, true),
('DabGo', null, null, null, null, null, true),
('Dank', null, null, null, null, null, true),
('DaySavers', null, null, null, null, null, true),
('Dayzed', null, null, null, null, null, true),
('Dogwalkers', 'Premium mini pre-roll brand inspired by founder Ben Kovler''s dog walks.', 'Multi-state (Cresco Labs)', 'Mini pre-rolls perfect for short sessions, animal shelter donations', 'Pre-rolls', ARRAY['Mini 0.35g pre-rolls - perfect for a quick session','Named after the founder''s habit of smoking during dog walks','They donate to animal shelters','Consistent dosing every time - great for portion control'], true),
('Domes', null, 'Kingston, NY', 'Our house brand!', null, ARRAY['That''s us! Support the home team','Ask customers about their favorite Domes products'], true),
('Dr. Jekyll & Mr. High', null, null, null, null, null, true),
('Dr. Solomons', null, null, null, null, null, true),
('Dragonfly', null, null, null, null, null, true),
('Drew Martin', null, null, null, null, null, true),
('Eaton Botanicals', 'Low-dose THC gummies infused with adaptogenic mushrooms from a family farm.', 'Eaton, NY', 'Functional wellness cannabis with adaptogenic supplements, nano-fast effects', 'Gummies', ARRAY['First functional wellness cannabis brand in New York','Combines THC with adaptogenic mushrooms','Effects kick in within 15-30 minutes thanks to nano technology','Perfect for wellness-minded customers'], true),
('Edie Parker', null, null, null, null, null, true),
('Elements', null, null, null, null, null, true),
('Eureka', null, null, null, null, null, true),
('FLAMER', null, null, null, null, null, true),
('FOY', null, null, null, null, null, true),
('Feels', null, null, null, null, null, true),
('Fernway', null, null, null, null, null, true),
('Finca', null, null, null, null, null, true),
('Find', null, null, null, null, null, true),
('Flaunt', null, null, null, null, null, true),
('Flo Extracts', null, null, null, null, null, true),
('Florist Farms', 'First legal cannabis brand sold in New York State, grown organically on a regenerative farm.', 'Cortland, NY', 'Organic farming, solar-powered facility, first legal NY brand', 'Flower, Vapes, Pre-rolls', ARRAY['FIRST legal cannabis brand sold in New York State!','100% organic - no pesticides or chemicals','Solar-powered growing facility','Regenerative farming practices that improve the soil'], true),
('Flowerhouse', null, null, null, null, null, true),
('Formula 420', null, null, null, null, null, true),
('Gallery Books', null, null, null, null, null, true),
('Generic AF', null, null, null, null, null, true),
('Gentlemen Smugglers', null, null, null, null, null, true),
('Glob Mops', null, null, null, null, null, true),
('Good Green', 'New York cannabis brand committed to social equity and community investment.', 'New York', 'Premium cannabis with social justice focus', 'Flower, Pre-rolls', ARRAY['Committed to social equity in the cannabis industry','Community investment and education programs','Supports expungement initiatives','Premium quality with a purpose'], true),
('Good Tide', null, null, null, null, null, true),
('Goodlyfe', null, null, null, null, null, true),
('Grassie', null, null, null, null, null, true),
('Grassroots', 'Premium cannabis brand from Curaleaf with craft-inspired genetics.', 'Multi-state', 'Craft-inspired flower and concentrates with bold terpene profiles', 'Flower, Pre-rolls, Concentrates', ARRAY['Craft-inspired approach to cannabis genetics','Known for bold terpene profiles - lots of flavor','Part of the Curaleaf family','Great for customers who appreciate unique strains'], true),
('Green Goat Gardens', null, null, null, null, null, true),
('Green Revolution', null, null, null, null, null, true),
('Grön', 'Artisanal cannabis edibles producing premium Fair Trade certified chocolate bars and gummies.', 'Portland, OR', 'Premium chocolates and gummies with real fruit ingredients', 'Chocolates, Gummies', ARRAY['Fair Trade certified cannabis chocolate - rare in the industry','Uses real fruit ingredients in their gummies','Artisanal quality - small batch production','Great gift option with premium packaging'], true),
('Hai', null, null, null, null, null, true),
('Happy Hounds', null, null, null, null, null, true),
('Harney Brothers', 'From the Harney & Sons tea family in Millerton NY, blending sun-grown Hudson Valley cannabis with tea traditions.', 'Millerton, NY', 'Tea sachets, tinctures, and beverages combining cannabis and tea', 'Beverages, Tinctures, Tea sachets', ARRAY['From the famous Harney & Sons tea family!','Sun-grown cannabis right here in the Hudson Valley','Unique tea sachet products - cannabis meets fine tea','Great story to tell customers - generations of craftsmanship'], true),
('Head & Heal', 'Seed-to-sale tincture brand from an organic farm focused on functional wellness.', 'Cortland, NY', 'Functional tinctures for Relief, Sleep, Focus', 'Tinctures', ARRAY['Seed-to-sale - they control every step','Functional tinctures targeting specific needs: Relief, Sleep, Focus','Regeneratively grown cannabis','Vegan formulations'], true),
('Heavy Hitters', 'Family-owned vape brand established in 1996 known for high-potency cartridges.', 'Bay Area, CA', '90-95% THC vapes without cutting agents, 10M+ units sold', 'Vapes', ARRAY['90-95% THC in their vapes - among the highest potency available','No cutting agents - pure cannabis oil','Family-owned since 1996','Over 10 million units sold'], true),
('Hemper', null, null, null, null, null, true),
('Hepworth', null, null, null, null, null, true),
('Her Highness', null, null, null, null, null, true),
('HiCOLOR', null, null, null, null, null, true),
('High Hemp Wraps', null, null, null, null, null, true),
('High Peaks', null, null, null, null, null, true),
('Highland Goat', null, null, null, null, null, true),
('Honey Dog Heaven', null, null, null, null, null, true),
('House of Sacci', null, null, null, null, null, true),
('Hudson Cannabis', 'Regenerative organic farm on 500 acres, first climate-positive cannabis cultivation in the world.', 'Hudson, NY', 'Climate-positive cultivation, indica-leaning cultivars', 'Flower, Pre-rolls', ARRAY['First climate-positive cannabis farm in the WORLD','500-acre regenerative organic operation','Right here in the Hudson Valley','Their growing practices actually improve the environment'], true),
('Hurley Grown', 'Sun-grown cannabis from Hurley Flats in Ulster County, certified organic since 2017.', 'Hurley, NY (Ulster County)', 'Sun-grown organic flower from Hurley Flats', 'Flower', ARRAY['Grown right here in Ulster County - super local!','Certified organic since 2017','Sun-grown on Hurley Flats','Support your neighbors - they''re practically down the road'], true),
('Illuminated Leaf', null, null, null, null, null, true),
('Incredibles', 'Award-winning Colorado edibles brand offering handcrafted chocolates, gummies, and mints.', 'Colorado', 'Vegan/gluten-free handcrafted edibles, 10 segments per chocolate bar', 'Chocolates, Gummies, Mints', ARRAY['Award-winning edibles since 2010','Chocolate bars come in 10 breakable segments for easy dosing','Vegan and gluten-free options available','Handcrafted quality you can taste'], true),
('Ithaca Organics', null, null, null, null, null, true),
('Jaunty', null, null, null, null, null, true),
('Jeeter', 'Infused pre-rolls combining flower with liquid diamonds concentrate.', 'Desert Hot Springs, CA', '#1 pre-roll brand in America, liquid diamonds infusion', 'Pre-rolls', ARRAY['Claims to be the #1 pre-roll brand in America','Infused with liquid diamonds - their proprietary concentrate','Extra potent compared to regular pre-rolls','Great for experienced customers wanting more kick'], true),
('Jetpacks', null, null, null, null, null, true),
('Jetty', 'Pioneer in solventless vape technology using ice and water extraction.', 'Oakland, CA', 'Solventless vapes with 75% market share in CA, cancer patient donation program', 'Vapes', ARRAY['Pioneer of solventless vape technology','They use only ice and water for extraction - totally clean','75% solventless vape market share in California','They donate products to cancer patients - great mission'], true),
('Jive', null, null, null, null, null, true),
('Karmic Glassworks', null, null, null, null, null, true),
('Kings & Queens', null, null, null, null, null, true),
('Kiva', 'Artisanal cannabis confections known for premium chocolate bars and edibles.', 'California', '#1 edibles brand in the country, premium chocolates and gummies', 'Chocolates, Gummies, Mints', ARRAY['#1 edibles brand in the country','Their chocolate bars are artisanal quality','Parent company of Camino and Lost Farm','Great entry point for edibles customers who want quality'], true),
('Klaus', null, null, null, null, null, true),
('Knack', null, null, null, null, null, true),
('Koa', null, null, null, null, null, true),
('Kushkards', null, null, null, null, null, true),
('Lail Design', null, null, null, null, null, true),
('Leal', null, null, null, null, null, true),
('Left Coast', null, null, null, null, null, true),
('Lion Order', null, null, null, null, null, true),
('Littles', null, null, null, null, null, true),
('Lookah', null, null, null, null, null, true),
('Lost Farm', 'Strain-specific edibles by Kiva Confections using 100% live resin and rosin.', 'Multi-state', 'Live resin/rosin gummies with strain-specific terpenes, no distillate', 'Gummies', ARRAY['100% live resin or rosin - never distillate','Each gummy has strain-specific terpene profiles','Made by Kiva Confections - premium quality','Closest edible experience to smoking a specific strain'], true),
('Lowell Herb Co', 'Founded 2017, California brand now cultivating in Hudson Valley NY, known for premium pre-rolls and flower.', 'Hudson Valley, NY (originally CA)', 'Premium pre-rolls, flower, and concentrates', 'Flower, Pre-rolls, Concentrates', ARRAY['Originally from California, now growing right here in the Hudson Valley','Known for their beautiful pre-roll packs','Premium flower with careful cultivation','One of the most Instagram-famous cannabis brands'], true),
('Luci', null, null, null, null, null, true),
('Lucky Sun Farms', null, null, null, null, null, true),
('Lussi', null, null, null, null, null, true),
('LuvBuds', null, null, null, null, null, true),
('MFNY', 'Marijuana Farms New York - 110K+ sq ft cultivation facility, #1 concentrates brand in NY.', 'New Windsor, NY', 'Seed-to-shelf, #1 concentrates in NY', 'Flower, Concentrates, Vapes', ARRAY['#1 concentrates brand in all of New York','Massive 110K+ square foot growing facility in New Windsor','Seed-to-shelf - they control the entire process','Local NY brand doing it big'], true),
('MSM', null, null, null, null, null, true),
('Mac Pharms', null, null, null, null, null, true),
('Mamba', null, null, null, null, null, true),
('Mildly Moronic', null, null, null, null, null, true),
('Misty Bleu', null, null, null, null, null, true),
('My Bud Vase', null, null, null, null, null, true),
('NY Honey', null, null, null, null, null, true),
('Naka', null, null, null, null, null, true),
('Nanticoke', 'Cannabis cultivator run by the Shafer brothers, transitioning their family farm to cannabis.', 'Endicott, NY', 'Greenhouse-grown diverse product portfolio', 'Flower, Pre-rolls, Vapes, Edibles', ARRAY['Family farm converted to cannabis cultivation','Greenhouse-grown for quality and sustainability','Diverse product line - flower, pre-rolls, vapes, and edibles','Proud NY-based diverse cannabis company'], true),
('Native Nations', null, null, null, null, null, true),
('No Bad Daze', null, null, null, null, null, true),
('Nom Nom Edible Co.', null, null, null, null, null, true),
('Nyce', null, null, null, null, null, true),
('Off Hours', 'NY-based brand with fast-acting nano-enhanced edibles and live rosin gummies.', 'New York', 'Nano-enhanced fast-acting edibles, vegan and gluten-free', 'Gummies, Edibles', ARRAY['Nano-enhanced means effects hit in 15-20 minutes','Live rosin gummies - premium extraction','Vegan and gluten-free','Great for customers who don''t want to wait an hour for edibles'], true),
('Old Pal', 'Cannabis lifestyle brand focused on simplicity and shareability at accessible prices.', 'Venice Beach, CA', 'Classic flower and pre-rolls, community-focused, affordable', 'Flower, Pre-rolls, Edibles', ARRAY['Community-focused brand - cannabis is meant to be shared','Affordable pricing without sacrificing quality','Simple, no-frills approach to cannabis','Available in 12+ states'], true),
('Olio', null, null, null, null, null, true),
('One Hitter', null, null, null, null, null, true),
('Ongrok', null, null, null, null, null, true),
('Ooze', null, null, null, null, null, true),
('Operator Canna Co.', null, null, null, null, null, true),
('Out East Canna', null, null, null, null, null, true),
('Ozium', null, null, null, null, null, true),
('PAX', 'Premium cannabis vaporizer brand often called "the iPhone of vaporizers."', 'San Francisco, CA', 'Award-winning portable vaporizers for dry herb and oils', 'Vaporizers', ARRAY['Called the iPhone of vaporizers - sleek and premium','Works with dry herb and oil pods','Bluetooth app control for precise temperature','Great for customers who want a discreet, high-tech experience'], true),
('PUFF', null, null, null, null, null, true),
('Packs', null, null, null, null, null, true),
('Phil''s Nice', null, null, null, null, null, true),
('Piece Water', null, null, null, null, null, true),
('Pixlz', null, null, null, null, null, true),
('Plantwerks', null, null, null, null, null, true),
('Pot & Head', null, null, null, null, null, true),
('Protab', null, null, null, null, null, true),
('Puff Palz', null, null, null, null, null, true),
('Puffco', null, null, null, null, null, true),
('Pulsar', null, null, null, null, null, true),
('Pura', null, null, null, null, null, true),
('RAW', null, null, null, null, null, true),
('REMZzz', null, null, null, null, null, true),
('Ready 2 Roll', null, null, null, null, null, true),
('Real Life Botanicals', null, null, null, null, null, true),
('Revelry', null, null, null, null, null, true),
('Revert', null, null, null, null, null, true),
('Rolling Green', null, null, null, null, null, true),
('Rove', null, null, null, null, null, true),
('Ruby Farms', null, null, null, null, null, true),
('Rythm', 'Flagship premium cannabis brand from Green Thumb Industries (GTI).', 'Multi-state', '#1 flower brand in the world, full-spectrum vapes and live resin', 'Flower, Vapes, Concentrates', ARRAY['#1 flower brand in the WORLD','Full-spectrum vapes with no fillers','From Green Thumb Industries - major cannabis company','Consistent quality across all their products'], true),
('Sackville', null, null, null, null, null, true),
('Sapphire', null, null, null, null, null, true),
('Select', 'Premium cannabis vape and oil brand owned by Curaleaf, available in 15+ states.', 'Multi-state', 'High-quality vape oils and innovative edibles', 'Vapes, Edibles', ARRAY['Available in 15+ states - massive reach','Premium vape oil quality','Part of the Curaleaf family','Consistent experience every time'], true),
('SiLLY NiCE', null, null, null, null, null, true),
('Skyrose Farm', null, null, null, null, null, true),
('Sluggers', null, null, null, null, null, true),
('Smoakland', null, null, null, null, null, true),
('Smoke Temple', null, null, null, null, null, true),
('Smokiez', null, null, null, null, null, true),
('Smyle Labs', null, null, null, null, null, true),
('Soft Power Sweets', null, null, null, null, null, true),
('Space Poppers', null, null, null, null, null, true),
('Spacebuds', null, null, null, null, null, true),
('Stache', null, null, null, null, null, true),
('Stash Queens', null, null, null, null, null, true),
('State Of Mind', null, null, null, null, null, true),
('Stay Melo', null, null, null, null, null, true),
('Stiiizy', 'Premium cannabis brand that pioneered the pod-based vape system.', 'Los Angeles, CA', 'Pod-based vape systems, largest retail cannabis chain in California', 'Vapes, Flower, Edibles', ARRAY['Pioneered the pod vape system - super easy to use','Largest retail cannabis chain in California','Premium quality across all product types','Their pods are proprietary - customers need Stiiizy battery'], true),
('Stone Road', 'Queer-run premium cannabis brand focused on sustainability with sun-grown flower.', 'Nevada City, CA', 'Sun-grown biodynamic flower, hand-rolled pre-rolls', 'Flower, Pre-rolls', ARRAY['Queer-run brand with strong values','Biodynamic farming - beyond organic','Hand-rolled pre-rolls','Minimalist, sustainable packaging'], true),
('Sugarhouse Farms', null, null, null, null, null, true),
('Sundrift', null, null, null, null, null, true),
('Supernaturals', null, null, null, null, null, true),
('Sushi Hash', null, null, null, null, null, true),
('THC Supply Co.', null, null, null, null, null, true),
('THERAPY', null, null, null, null, null, true),
('The Botanist', null, null, null, null, null, true),
('The Bulk Boys', null, null, null, null, null, true),
('The Green Lady', null, null, null, null, null, true),
('The Healing Rose', null, null, null, null, null, true),
('Toast', 'Multi-state premium pre-roll brand with refined craftsmanship and thoughtful genetics.', 'Multi-state', 'Premium pre-rolls with hemp paper filters', 'Pre-rolls', ARRAY['Premium pre-rolls with hemp paper filters','Consistent quality across multiple states','Thoughtful genetics selection','Refined craftsmanship in every roll'], true),
('Torched Life', null, null, null, null, null, true),
('Torrwood Farm', null, null, null, null, null, true),
('Tune', null, null, null, null, null, true),
('Umamii', null, null, null, null, null, true),
('Unblushing', null, null, null, null, null, true),
('Untitled', null, null, null, null, null, true),
('Upstate Mary', null, null, null, null, null, true),
('Veterans Choice Creations', null, null, null, null, null, true),
('Vireo', 'Medical cannabis pioneer in New York founded by Dr. Kyle Kingsley.', 'White Plains, NY', 'Pharmaceutical-grade extracts and medical cannabis products', 'Flower, Vapes, Tinctures, Edibles', ARRAY['Medical cannabis pioneer in New York','Founded by a doctor - pharmaceutical-grade quality','Strong focus on environmental sustainability','Great for medically-minded customers'], true),
('WYLD', 'Real-fruit cannabis gummies, #1 cannabis gummy brand in the US.', 'Portland, OR', '#1 gummy brand in the US, real-fruit with specific effect formulations', 'Gummies', ARRAY['#1 cannabis gummy brand in the entire US','Made with real fruit - you can taste the difference','Vegan pectin formulations','Different varieties for different effects'], true),
('Wana', 'Cannabis edibles founded in 2010 with precision-dosed vegan gummies.', 'Boulder, CO', 'Precision-dosed gummies, fastest-growing edibles company in North America', 'Gummies', ARRAY['Fastest-growing edibles company in North America','Precision-dosed for consistent experience every time','Vegan gummies','Been in the game since 2010 - proven track record'], true),
('Weed Water', null, null, null, null, null, true),
('Woodstock', null, null, null, null, null, true),
('Wulf', null, null, null, null, null, true),
('Yocan', null, null, null, null, null, true),
('Zig Zag', null, null, null, null, null, true),
('mini MART', null, null, null, null, null, true),
('oHHo', null, null, null, null, null, true)
ON CONFLICT (name) DO UPDATE SET
  description = COALESCE(EXCLUDED.description, brands.description),
  location = COALESCE(EXCLUDED.location, brands.location),
  known_for = COALESCE(EXCLUDED.known_for, brands.known_for),
  product_types = COALESCE(EXCLUDED.product_types, brands.product_types),
  talking_points = COALESCE(EXCLUDED.talking_points, brands.talking_points);
