/**
 * Cannabis Definitions
 * Maps every word in the cannabis dictionary to a short,
 * cannabis-specific definition (1 sentence, under 20 words).
 * For budtender education and in-app tooltips.
 */

export const CANNABIS_DEFINITIONS: Record<string, string> = {
  // ── Strains ──
  'ace': 'A sativa-dominant strain known for its uplifting, energetic, and cerebral high.',
  'acdc': 'A high-CBD strain with minimal psychoactive effects, popular for pain relief.',
  'afghan': 'A pure indica landrace strain from Afghanistan with heavy, sedating body effects.',
  'afpak': 'An indica cross of Afghani and Pakistani landrace strains with earthy, relaxing effects.',
  'amnesia': 'A potent sativa-dominant strain famous for hazy, euphoric, and cerebral effects.',
  'animal': 'A family of potent hybrid strains like Animal Mints known for heavy relaxation.',
  'ape': 'Short for Grape Ape, a purple indica with grape flavor and strong sedation.',
  'apple': 'A fruity hybrid strain family like Apple Fritter with sweet, relaxing effects.',
  'banana': 'A tropical hybrid strain family like Banana OG known for mellow, happy effects.',
  'biscotti': 'A cookie-lineage indica hybrid with sweet, diesel flavors and relaxing effects.',
  'biscuit': 'A doughy, sweet indica-hybrid strain with calming and euphoric qualities.',
  'blackberry': 'A fruity indica strain with berry aroma and deeply relaxing body effects.',
  'blueberry': 'A legendary indica strain with sweet berry flavor and tranquil body effects.',
  'bruce': 'Short for Bruce Banner, a potent sativa-hybrid named for its incredible strength.',
  'bubba': 'Short for Bubba Kush, a classic indica with heavy sedation and coffee flavor.',
  'bubblegum': 'A balanced hybrid with sweet bubblegum flavor and euphoric, relaxing effects.',
  'cake': 'A strain family like Wedding Cake known for rich, sweet, indica-dominant effects.',
  'candy': 'A sweet-flavored hybrid strain family with balanced euphoric and relaxing effects.',
  'cereal': 'A hybrid strain like Cereal Milk with creamy, sweet flavor and balanced effects.',
  'cheese': 'A pungent indica-hybrid strain with sharp, cheesy aroma and relaxing effects.',
  'cheetah': 'A fast-hitting sativa-hybrid strain named for its rapid onset of euphoria.',
  'chemdog': 'A legendary hybrid strain with diesel aroma that parented OG Kush and Sour Diesel.',
  'cherry': 'A fruity strain family like Cherry Pie with sweet flavor and balanced effects.',
  'chocolate': 'A rich, earthy strain family with cocoa undertones and relaxing effects.',
  'citrus': 'A bright, limonene-rich strain family with uplifting and energizing effects.',
  'cookie': 'A single-form reference to the Girl Scout Cookies lineage of hybrid strains.',
  'cookies': 'A famous hybrid strain family originating from GSC with sweet, euphoric effects.',
  'cream': 'A smooth, creamy strain family like Cookies and Cream with balanced effects.',
  'critical': 'A high-yielding indica-dominant strain known for dense buds and relaxing effects.',
  'crush': 'A fruity hybrid strain family like Orange Crush with uplifting, citrus effects.',
  'diesel': 'A pungent sativa strain family with fuel-like aroma and energizing cerebral effects.',
  'dosido': 'An indica-dominant hybrid with sweet, earthy flavor and heavy body relaxation.',
  'dream': 'A strain family like Blue Dream, one of the most popular sativa-dominant hybrids.',
  'durban': 'A pure sativa landrace from South Africa with sweet, uplifting, energetic effects.',
  'fire': 'Slang for exceptionally high-quality cannabis with great flavor, potency, and appearance.',
  'fruity': 'A terpene-rich strain family like Fruity Pebbles with sweet, tropical flavors.',
  'fuel': 'A descriptor for strains with pungent, gasoline-like aromas from caryophyllene terpenes.',
  'gas': 'Slang for potent, pungent cannabis with strong fuel-like or diesel aromas.',
  'gelato': 'A dessert hybrid strain with sweet, creamy flavor and balanced euphoric effects.',
  'ghost': 'A strain like Ghost OG or Ghost Train Haze known for potent, hazy effects.',
  'glue': 'Short for Gorilla Glue, a sticky hybrid with heavy resin and couch-lock effects.',
  'gorilla': 'Short for Gorilla Glue #4, a resinous hybrid famous for potent relaxation.',
  'grape': 'A fruity indica strain family with purple hues, grape flavor, and calming effects.',
  'grapefruit': 'A citrusy sativa strain with tangy grapefruit flavor and uplifting, energetic effects.',
  'gsc': 'Girl Scout Cookies, a legendary hybrid with sweet, earthy flavor and euphoria.',
  'guava': 'A tropical hybrid strain with exotic fruit flavor and balanced, happy effects.',
  'gummy': 'A candy-flavored hybrid strain with sweet taste and giggly, euphoric effects.',
  'haze': 'A classic sativa strain family known for cerebral, creative, and energizing effects.',
  'headband': 'A hybrid strain named for the pressure sensation around the forehead it produces.',
  'hulk': 'Short for Bruce Banner or Incredible Hulk, a powerfully potent sativa-hybrid strain.',
  'ice': 'A frosty, trichome-heavy indica strain with cool menthol undertones and relaxation.',
  'jack': 'Short for Jack Herer, a beloved sativa named after the cannabis activist.',
  'jealousy': 'A potent hybrid strain with gassy, creamy flavor and balanced euphoric effects.',
  'jet': 'A fast-acting strain like Jet Fuel with diesel aroma and energizing effects.',
  'king': 'A strain prefix like King Louis, typically indicating potent indica-dominant effects.',
  'kryptonite': 'A super-potent indica strain that can leave users immobilized on the couch.',
  'kush': 'A family of indica-dominant strains originating from the Hindu Kush mountain region.',
  'larry': 'Short for Larry OG, an indica-dominant hybrid with piney, earthy relaxation.',
  'lavender': 'A floral indica strain with calming lavender aroma and soothing body effects.',
  'lemon': 'A citrusy strain family like Lemon Haze with bright, uplifting sativa effects.',
  'lime': 'A zesty, citrus-flavored strain with limonene-forward terpenes and energizing effects.',
  'london': 'A strain prefix as in London Pound Cake, an indica with sweet, berry flavor.',
  'mac': 'Miracle Alien Cookies, a balanced hybrid with creamy flavor and euphoric effects.',
  'mango': 'A tropical indica strain with sweet mango flavor and deeply relaxing body effects.',
  'maui': 'Short for Maui Wowie, a classic Hawaiian sativa with tropical, uplifting effects.',
  'melon': 'A fruity hybrid strain with sweet melon flavor and balanced, relaxing effects.',
  'mimosa': 'A sativa-dominant hybrid with citrus-champagne flavor and uplifting morning effects.',
  'mint': 'A cool, menthol-flavored strain family with refreshing terpene profiles.',
  'mochi': 'A dessert hybrid strain with sweet, creamy flavor and balanced mind-body effects.',
  'moonrock': 'Cannabis buds dipped in concentrate and rolled in kief for extreme potency.',
  'northern': 'Short for Northern Lights, a legendary pure indica with dreamy, sedating effects.',
  'nuken': 'A Canadian indica-dominant hybrid with sweet, marshmallow aroma and heavy relaxation.',
  'obama': 'Short for Obama Kush, an indica strain with grape and berry relaxing effects.',
  'ocean': 'A strain prefix as in Ocean Grown (OG) indicating premium coastal cannabis genetics.',
  'orange': 'A citrus strain family like Agent Orange with sweet, tangy, uplifting effects.',
  'oreo': 'A cookies-lineage hybrid with sweet, creamy flavor and balanced euphoric effects.',
  'papaya': 'A tropical indica-dominant strain with sweet papaya flavor and sedating effects.',
  'peach': 'A fruity hybrid strain with sweet peach flavor and mellow, happy effects.',
  'pebbles': 'Short for Fruity Pebbles, a rare hybrid with rainbow colors and sweet flavor.',
  'pie': 'A strain suffix as in Cherry Pie, indicating sweet, dessert-like flavor profiles.',
  'pine': 'A woodsy, pinene-rich strain profile with sharp, forest-like aroma.',
  'pineapple': 'A tropical sativa strain with sweet pineapple flavor and uplifting, creative effects.',
  'plum': 'A fruity indica strain with dark purple hues and sweet, relaxing effects.',
  'poison': 'A strain name as in Durban Poison, a pure energizing South African sativa.',
  'punch': 'A strain suffix as in Purple Punch, indicating sweet, fruity, knockout effects.',
  'purple': 'A strain family with anthocyanin-rich purple hues, often indicating relaxing indicas.',
  'rainbow': 'A colorful hybrid strain with varied terpenes and balanced, euphoric effects.',
  'razz': 'A raspberry-flavored strain with sweet, berry terpenes and uplifting effects.',
  'rocket': 'A fast-acting sativa strain known for its rapid, sky-high cerebral effects.',
  'runtz': 'A hugely popular hybrid strain with candy flavor and balanced euphoric effects.',
  'sherbert': 'A dessert indica-hybrid strain with sweet, creamy flavor and relaxing effects.',
  'skittlez': 'A fruity indica with candy-sweet flavor and calming, full-body relaxation.',
  'skunk': 'A pungent classic hybrid strain known for its unmistakable skunky aroma.',
  'slurricane': 'A potent indica hybrid with sweet berry flavor and heavily sedating effects.',
  'snowcap': 'A frosty sativa-dominant hybrid with menthol, citrus flavor and uplifting effects.',
  'sour': 'A strain prefix as in Sour Diesel, indicating tart, pungent flavor profiles.',
  'stardawg': 'A potent sativa-dominant hybrid with diesel, pine aroma and cerebral effects.',
  'strawberry': 'A fruity hybrid strain with sweet strawberry aroma and euphoric, uplifting effects.',
  'sugar': 'A crystalline cannabis concentrate or a strain with exceptionally frosty trichomes.',
  'sunset': 'A strain prefix as in Sunset Sherbert with sweet, relaxing evening effects.',
  'supreme': 'A premium-grade strain designation indicating top-shelf quality and potency.',
  'tangie': 'A citrusy sativa strain with bright tangerine flavor and creative, uplifting effects.',
  'tiger': 'A striped, colorful hybrid strain with exotic terpenes and potent effects.',
  'trainwreck': 'A potent sativa-dominant hybrid known for its intense, fast-hitting cerebral rush.',
  'truffle': 'An earthy, rich hybrid strain with savory flavor and relaxing body effects.',
  'tuna': 'Short for Tuna Kush, a pungent indica with fishy aroma and heavy sedation.',
  'vanilla': 'A sweet, creamy strain with smooth vanilla terpenes and calming body effects.',
  'velvet': 'A smooth, luxurious strain known for its silky smoke and mellow effects.',
  'venom': 'A potent strain with an intense, fast-striking high and pungent aroma.',
  'watermelon': 'A fruity indica strain with sweet watermelon flavor and relaxing body effects.',
  'wedding': 'A strain prefix as in Wedding Cake, a potent indica-hybrid with sweet flavor.',
  'white': 'A strain prefix as in White Widow, indicating frosty, trichome-covered buds.',
  'widow': 'Short for White Widow, a legendary balanced hybrid with resinous, potent buds.',
  'wizard': 'A mystical hybrid strain known for its magical, creative, and euphoric effects.',
  'yoda': 'An indica-dominant strain like Yoda OG with wise, deeply meditative sedation.',
  'zen': 'A calming strain or the state of peaceful, meditative balance from cannabis.',
  'zero': 'A strain like Absolute Zero or descriptor for zero-THC CBD products.',
  'zkittlez': 'An award-winning indica with candy-sweet flavor and calming, happy effects.',
  'zombie': 'A heavily sedating indica strain that leaves users in a couch-locked stupor.',
  'zookies': 'A cookies-lineage hybrid with sweet, nutty flavor and balanced euphoric effects.',

  // ── Terpenes ──
  'bisabolol': 'A floral terpene with chamomile-like aroma that promotes calm and skin healing.',
  'borneol': 'A minty, herbal terpene with cooling effects used in traditional medicine.',
  'camphene': 'An earthy, woodsy terpene with musky aroma found in cooling, soothing strains.',
  'carene': 'A sweet, cedar-scented terpene known for drying effects and bone health support.',
  'caryophyllene': 'A spicy, peppery terpene that binds to CB2 receptors for anti-inflammatory relief.',
  'cymene': 'A citrusy, woody terpene with mild antibacterial properties found in cumin.',
  'eucalyptol': 'A cooling, minty terpene with eucalyptus aroma that aids respiratory function.',
  'farnesene': 'A green-apple-scented terpene with calming, sedative properties found in some strains.',
  'fenchol': 'An herbal, basil-scented terpene with antibacterial and antioxidant properties.',
  'geraniol': 'A sweet, rosy terpene with floral aroma that repels insects and reduces inflammation.',
  'guaiol': 'A piney, woody terpene with anti-inflammatory and antimicrobial properties.',
  'humulene': 'A hoppy, earthy terpene known for appetite suppression and anti-inflammatory effects.',
  'limonene': 'A bright citrus terpene that elevates mood and relieves stress and anxiety.',
  'linalool': 'A floral, lavender terpene that promotes relaxation, calm, and sleep.',
  'myrcene': 'An earthy, musky terpene that enhances THC absorption and promotes sedation.',
  'nerolidol': 'A woody, floral terpene with sedative effects and skin-penetration-enhancing properties.',
  'ocimene': 'A sweet, herbaceous terpene with uplifting effects and antifungal properties.',
  'phytol': 'A grassy, floral terpene created when chlorophyll breaks down during drying.',
  'pinene': 'A sharp, piney terpene that promotes alertness and counteracts THC memory impairment.',
  'pulegone': 'A minty terpene with peppermint aroma found in small amounts in some strains.',
  'sabinene': 'A spicy, woody terpene with peppery notes found in oak and some cannabis.',
  'terpinene': 'A citrusy, herbal terpene with antioxidant properties found in tea tree.',
  'terpineol': 'A floral, lilac-scented terpene with relaxing, sedative, and calming effects.',
  'terpinolene': 'A complex piney-floral terpene with uplifting effects found in sativa strains.',
  'valencene': 'A sweet, citrusy terpene with orange aroma and anti-inflammatory properties.',

  // ── Cannabinoids ──
  'thc': 'Delta-9-tetrahydrocannabinol, the primary psychoactive cannabinoid that produces the high.',
  'thca': 'The raw, non-psychoactive precursor to THC found in fresh cannabis flower.',
  'thcv': 'A minor cannabinoid that suppresses appetite and provides short, energetic effects.',
  'thcp': 'A rare cannabinoid reported to be up to 33 times more potent than THC.',
  'cbd': 'Cannabidiol, a non-psychoactive cannabinoid used for pain, anxiety, and inflammation relief.',
  'cbda': 'The raw, acidic precursor to CBD found in unheated fresh cannabis plant material.',
  'cbdv': 'A minor cannabinoid similar to CBD being studied for nausea and seizure reduction.',
  'cbg': 'Cannabigerol, the "mother cannabinoid" precursor to THC and CBD with anti-inflammatory effects.',
  'cbga': 'The acidic precursor to CBG and the origin molecule for all other cannabinoids.',
  'cbn': 'Cannabinol, a mildly sedating cannabinoid formed as THC ages and degrades.',
  'cbc': 'Cannabichromene, a non-psychoactive cannabinoid with pain-relieving and antidepressant potential.',
  'delta': 'Prefix for delta-8 or delta-9 THC variants with different psychoactive potencies.',

  // ── Effects & Feelings ──
  'alert': 'A clear-headed, wakeful effect often produced by sativa-dominant strains.',
  'awake': 'A stimulating effect that fights drowsiness, common in energizing sativa strains.',
  'bliss': 'A state of deep euphoric contentment and happiness from cannabis consumption.',
  'body': 'Physical sensation effects centered in the body rather than the mind.',
  'boost': 'An energizing lift in mood or energy from uplifting cannabis strains.',
  'brave': 'A confidence-enhancing effect that reduces social anxiety from certain strains.',
  'bright': 'A clear, vivid mental effect with enhanced sensory perception from sativas.',
  'buzz': 'A mild, pleasant psychoactive sensation at the onset of a cannabis high.',
  'calm': 'A soothing, anxiety-reducing effect common in indica and CBD-rich strains.',
  'chill': 'A relaxed, laid-back state without heavy sedation from balanced strains.',
  'clear': 'A focused, lucid high without mental fog from certain sativa strains.',
  'couch': 'Short for couch-lock, an intense body sedation making movement feel impossible.',
  'create': 'The urge to make or build things triggered by creativity-enhancing strains.',
  'creative': 'An effect that stimulates imagination and artistic thinking from sativa strains.',
  'deep': 'An intense, profound level of relaxation or introspection from potent strains.',
  'dopey': 'A goofy, mentally foggy effect from sedating indica-heavy strains.',
  'doze': 'A drowsy, sleep-inducing effect from heavy indica or CBN-rich products.',
  'drift': 'A gentle, floating sensation of mental wandering from relaxing strains.',
  'ease': 'Relief from tension, pain, or anxiety provided by therapeutic cannabis strains.',
  'elate': 'A mood-elevating, joyful effect from euphoria-inducing sativa strains.',
  'energy': 'An invigorating, stimulating effect that combats fatigue from sativa strains.',
  'euphoria': 'An intense feeling of happiness and well-being from THC-rich cannabis.',
  'float': 'A weightless, airy sensation of physical and mental lightness from cannabis.',
  'flow': 'A smooth, effortless state of focus and creativity from balanced strains.',
  'focus': 'Enhanced concentration and mental clarity from microdosing or sativa strains.',
  'free': 'A liberating, uninhibited feeling of mental release from cannabis consumption.',
  'fresh': 'A crisp, invigorating mental clarity from terpene-rich sativa strains.',
  'giddy': 'A lighthearted, silly feeling with uncontrollable laughter from certain strains.',
  'giggly': 'An effect causing fits of laughter and amusement, common in social strains.',
  'glow': 'A warm, radiating sense of well-being and contentment from cannabis.',
  'good': 'A general positive feeling of well-being and satisfaction from cannabis use.',
  'groove': 'An enhanced appreciation for music and rhythm from cerebral cannabis effects.',
  'happy': 'A mood-boosting effect that promotes positivity and joy from THC consumption.',
  'harmony': 'A balanced state where mind and body effects feel perfectly aligned.',
  'head': 'Cerebral effects focused in the mind rather than the body from sativas.',
  'heal': 'Therapeutic relief from physical or mental ailments through cannabis consumption.',
  'heavy': 'A strong, weighty body sensation indicating potent indica-dominant effects.',
  'high': 'The overall psychoactive experience produced by THC-containing cannabis products.',
  'ignite': 'A sudden burst of energy or creativity sparked by stimulating strains.',
  'inspire': 'A creative, motivational effect that sparks ideas from sativa-dominant strains.',
  'joy': 'A deep sense of happiness and gratitude enhanced by uplifting cannabis.',
  'juice': 'Slang for potency or the raw liquid extracted from fresh cannabis plants.',
  'keen': 'A sharpened, heightened sensory awareness from microdosing or sativa strains.',
  'lazy': 'A lethargic, unmotivated state from heavy indica or high-dose consumption.',
  'lean': 'A relaxed, tilted body sensation from moderately sedating cannabis effects.',
  'level': 'A balanced, steady state without extreme highs or lows from cannabis.',
  'lift': 'An upward shift in mood and energy from sativa or hybrid strains.',
  'light': 'A mild, gentle high with subtle effects from low-dose or CBD strains.',
  'lit': 'Slang for being pleasantly high and having a great time on cannabis.',
  'lock': 'Short for couch-lock, extreme sedation preventing physical movement from indicas.',
  'loose': 'A relaxed, tension-free state where muscles and mind feel unwound.',
  'love': 'Enhanced feelings of affection and emotional connection from certain strains.',
  'lucid': 'A clear-headed, aware high without confusion from balanced cannabis strains.',
  'mellow': 'A gentle, easy-going relaxation without heavy sedation from mild strains.',
  'mental': 'Effects concentrated in the mind such as creativity, focus, or euphoria.',
  'mind': 'Cerebral psychoactive effects that alter perception and thought patterns.',
  'mood': 'The emotional state influenced by cannabis, often elevated or stabilized.',
  'nap': 'A sleep-inducing effect strong enough to prompt a restful doze.',
  'numb': 'A pain-relieving, analgesic sensation that dulls physical discomfort from cannabis.',
  'peace': 'A serene, tranquil mental state free from stress or anxiety.',
  'peak': 'The maximum intensity point of a cannabis high before effects begin fading.',
  'pep': 'A perky, energetic boost in vitality from stimulating sativa strains.',
  'power': 'An intense, strong effect indicating high potency or dominant THC levels.',
  'quiet': 'A hushed, contemplative mental state from calming indica or CBD strains.',
  'relax': 'A tension-releasing effect that eases both body and mind from cannabis.',
  'relief': 'Reduction of pain, stress, or discomfort through therapeutic cannabis use.',
  'rest': 'A deeply calming effect that promotes sleep-readiness from indica strains.',
  'rise': 'An ascending, uplifting mental effect from energizing sativa strains.',
  'rush': 'A sudden, intense onset of euphoria or energy from potent strains.',
  'sedated': 'A heavily calmed, drowsy state from potent indica or CBN consumption.',
  'serene': 'A peaceful, undisturbed mental calm from soothing, balanced cannabis strains.',
  'sleepy': 'A drowsy, sleep-promoting effect common in indica and CBN-rich products.',
  'slow': 'A time-dilating, unhurried perception that makes everything feel decelerated.',
  'smooth': 'A gentle, non-harsh effect describing both smoke quality and mellow highs.',
  'snooze': 'A sleep-inducing effect that promotes deep, restful slumber from indicas.',
  'social': 'An effect that enhances sociability, conversation, and group enjoyment.',
  'soothe': 'A calming, comforting effect that eases discomfort and promotes relaxation.',
  'spark': 'An initial burst of creativity or energy at the start of a high.',
  'spirit': 'An uplifted, positive emotional effect that enhances overall well-being.',
  'stoned': 'A heavy, deeply relaxed state with full-body sedation from strong cannabis.',
  'surge': 'A wave of intensifying effects that builds during a cannabis experience.',
  'sweet': 'A pleasant, sugary flavor profile or a gentle, agreeable high.',
  'tingle': 'A buzzing, prickling physical sensation often felt at the onset of effects.',
  'tired': 'A fatigued, sleepy state induced by sedating indica or high-dose cannabis.',
  'tone': 'A subtle modulation of mood or physical sensation from cannabis effects.',
  'tranquil': 'A deeply peaceful, undisturbed calm from relaxing indica or CBD strains.',
  'trip': 'An intense psychoactive experience with altered perception from high-dose cannabis.',
  'tune': 'A heightened musical appreciation or sensory attunement from cannabis effects.',
  'unwind': 'The process of releasing tension and stress through relaxing cannabis consumption.',
  'uplift': 'A mood-elevating effect that raises spirits and energy from sativa strains.',
  'upbeat': 'A cheerful, positive, energized mood from stimulating sativa-dominant strains.',
  'vibe': 'The overall mood, energy, or atmosphere of a cannabis experience.',
  'vigor': 'A robust, energetic vitality from stimulating sativa or THCV-rich strains.',
  'vivid': 'Intensified colors, sounds, and sensory perception from psychoactive cannabis effects.',
  'warm': 'A cozy, comforting body sensation spreading through limbs from indica effects.',
  'wave': 'A rolling, pulsing pattern of cannabis effects that rise and fall.',
  'wavy': 'A flowing, undulating perceptual experience from moderate to strong cannabis.',
  'woke': 'A mentally alert, aware, and enlightened state from stimulating cannabis strains.',
  'wonder': 'A childlike sense of awe and curiosity enhanced by cannabis consumption.',
  'wow': 'An exclamation of amazement at the potency or quality of cannabis.',
  'zing': 'A sharp, energetic jolt of stimulation from fast-acting sativa strains.',
  'zone': 'A deep state of focused immersion or flow achieved through cannabis.',

  // ── Gear & Accessories ──
  'ash': 'The residue left after cannabis combustion in a bowl, joint, or blunt.',
  'ashtray': 'A receptacle for collecting ash and disposing of spent joints or bowls.',
  'banger': 'A quartz bucket attachment on a dab rig used to vaporize concentrates.',
  'battery': 'A rechargeable power source for vape pens and cartridge-based consumption devices.',
  'blunt': 'Cannabis rolled in a tobacco leaf or cigar wrap for smoking.',
  'bong': 'A water-filtered glass pipe used for smooth, cooled cannabis smoke inhalation.',
  'bowl': 'The rounded chamber on a pipe or bong where cannabis flower is packed.',
  'bubbler': 'A handheld glass pipe with water filtration combining bong and pipe features.',
  'burner': 'A dedicated lighter or torch used for igniting cannabis or heating dab nails.',
  'butane': 'A gas fuel used in lighters and torches, also used to extract concentrates.',
  'cap': 'A carb cap placed over a banger to regulate airflow during dabbing.',
  'carb': 'A small hole on a pipe that controls airflow and clears the chamber.',
  'cart': 'A pre-filled vape cartridge containing cannabis oil that attaches to a battery.',
  'chillum': 'A straight, one-piece hand pipe used for quick, simple smoking sessions.',
  'clipper': 'A popular refillable lighter brand favored by cannabis consumers for its poker tool.',
  'coil': 'The heating element inside a vape pen that vaporizes cannabis oil.',
  'cone': 'A pre-rolled paper shaped into a cone for easy cannabis flower filling.',
  'dab': 'A dose of cannabis concentrate vaporized on a hot surface for inhalation.',
  'dabber': 'A small tool used to place cannabis concentrate onto a heated banger or nail.',
  'dome': 'A glass cover placed over a nail to capture concentrate vapor for inhalation.',
  'domes': 'Glass vapor-capture covers for dab rigs, or the Domes Dispensary brand name.',
  'downstem': 'The glass tube connecting a bong bowl to the water chamber for filtration.',
  'dugout': 'A compact wooden box holding a one-hitter pipe and ground cannabis compartment.',
  'edible': 'A cannabis-infused food or drink product consumed orally for longer-lasting effects.',
  'filter': 'A tip or screen that prevents plant material from being inhaled while smoking.',
  'flame': 'The fire source from a lighter or match used to ignite cannabis flower.',
  'flint': 'The spark-producing component inside a lighter that ignites butane or hemp wick.',
  'glass': 'High-quality borosilicate smoking pieces like bongs, pipes, and dab rigs.',
  'globe': 'A spherical glass attachment for vape pens used with wax and concentrates.',
  'grinder': 'A multi-chambered tool that shreds cannabis flower into even, smokable pieces.',
  'hemp': 'Cannabis sativa grown for fiber, CBD, or wraps with under 0.3% THC.',
  'holder': 'A clip or device for holding joints or blunts during smoking sessions.',
  'hookah': 'A multi-hose water pipe sometimes used for smoking cannabis in social settings.',
  'jar': 'An airtight glass container used for storing and curing cannabis flower.',
  'joint': 'Cannabis flower rolled in thin paper, the most classic consumption method.',
  'kief': 'The loose trichome crystals sifted from cannabis flower, rich in cannabinoids.',
  'lighter': 'A portable flame device used to ignite cannabis flower in pipes or joints.',
  'liner': 'A protective insert placed inside storage containers to preserve cannabis freshness.',
  'mat': 'A silicone pad used as a non-stick surface for handling cannabis concentrates.',
  'mill': 'Another term for a grinder used to break down cannabis flower.',
  'mod': 'A modified or advanced vaporizer device with adjustable power and temperature settings.',
  'mold': 'A press shape for forming cannabis products, or unwanted fungal contamination.',
  'nail': 'A heated metal or quartz piece on a dab rig for vaporizing concentrates.',
  'nectar': 'Short for nectar collector, a portable dab straw for concentrates.',
  'oil': 'A liquid cannabis concentrate extracted from flower, used in vapes or edibles.',
  'paper': 'Thin rolling paper made from hemp, rice, or wood pulp for joints.',
  'papers': 'A pack of rolling papers used for hand-rolling cannabis joints.',
  'pen': 'A slim, pen-shaped vaporizer device for cannabis oil cartridges or concentrates.',
  'perc': 'A percolator inside a bong that adds extra water filtration and diffusion.',
  'piece': 'A general term for any glass smoking device like a pipe or bong.',
  'pipe': 'A handheld device with a bowl and mouthpiece for smoking cannabis flower.',
  'poker': 'A thin tool used to stir, pack, or clear cannabis from a bowl.',
  'pouch': 'A smell-proof carrying case for transporting cannabis products and accessories.',
  'press': 'A device that applies heat and pressure to make rosin from cannabis flower.',
  'puck': 'A compressed disc of cannabis material left after pressing rosin from flower.',
  'puff': 'A single inhalation of cannabis smoke or vapor from any consumption device.',
  'quartz': 'High-quality crystalline material used for dab bangers due to superior heat retention.',
  'rag': 'A cleaning cloth used to maintain and polish glass cannabis smoking devices.',
  'reclaim': 'Residual concentrate that collects inside a dab rig, salvageable for reuse.',
  'rig': 'A specialized water pipe designed specifically for vaporizing cannabis concentrates.',
  'ring': 'A glass joint connector or silicone band used on bongs and dab rigs.',
  'roach': 'The small remaining end of a smoked joint or blunt.',
  'roll': 'To wrap cannabis flower in paper or a blunt wrap for smoking.',
  'roller': 'A hand-operated device that helps roll uniform, consistent cannabis joints.',
  'scale': 'A precise digital weighing device for measuring cannabis portions and doses.',
  'screen': 'A small mesh filter placed in a bowl to prevent ash pull-through.',
  'shatter': 'A brittle, glass-like cannabis concentrate with high potency and clean flavor.',
  'slab': 'A large, flat piece of cannabis concentrate like shatter or wax.',
  'slider': 'A removable bowl piece on a bong that slides out to clear smoke.',
  'snuffer': 'A device for extinguishing a lit joint or blunt to save for later.',
  'spool': 'A roll of hemp wick used as a natural alternative to butane lighters.',
  'stem': 'The woody stalk of cannabis flower, typically removed before consumption.',
  'stir': 'To mix or agitate cannabis in a bowl, grinder, or edible preparation.',
  'straw': 'A tube-shaped dab tool like a nectar collector for inhaling concentrates.',
  'tab': 'A small, measured dose of cannabis in sublingual strip or edible form.',
  'tin': 'A metal container used for storing pre-rolls, edibles, or small accessories.',
  'tip': 'A filter or crutch at the mouthpiece end of a joint or blunt.',
  'toke': 'A single puff or inhalation of cannabis smoke or vapor.',
  'tool': 'Any implement used for packing, dabbing, cleaning, or handling cannabis products.',
  'torch': 'A high-heat butane flame used to heat dab nails and quartz bangers.',
  'tray': 'A flat surface used for rolling joints and organizing cannabis accessories.',
  'tube': 'A cylindrical pre-roll container or straight glass bong design.',
  'vape': 'A device that heats cannabis to produce inhalable vapor without combustion.',
  'vial': 'A small glass container for storing cannabis concentrates, tinctures, or oils.',
  'wick': 'A hemp cord lit and used as a butane-free flame source for smoking.',
  'wrap': 'A tobacco, hemp, or flavored leaf used to roll blunts around cannabis.',

  // ── Plant Anatomy & Cultivation ──
  'bract': 'The small leaf encasing the female cannabis flower that produces trichomes and resin.',
  'branch': 'A lateral growth extending from the main cannabis stalk bearing buds and leaves.',
  'breed': 'To cross-pollinate two cannabis strains to create new genetic varieties.',
  'bud': 'The dried, cured flower of the female cannabis plant consumed for its cannabinoids.',
  'bulb': 'A high-intensity grow light bulb used in cannabis indoor cultivation setups.',
  'calyx': 'The outermost part of the cannabis flower containing the highest trichome concentration.',
  'canopy': 'The upper layer of cannabis plant growth that receives direct light.',
  'clone': 'A genetic cutting taken from a mother cannabis plant for identical reproduction.',
  'cola': 'A cluster of buds growing tightly together at the top of a cannabis branch.',
  'compost': 'Decomposed organic matter used as nutrient-rich soil amendment for cannabis growing.',
  'crop': 'A batch of cannabis plants grown together during a single cultivation cycle.',
  'cure': 'The slow drying process in sealed jars that improves flavor and smoothness.',
  'cut': 'A clipping from a cannabis plant used for cloning or a specific genetic phenotype.',
  'dirt': 'Informal term for soil growing medium used in cannabis cultivation.',
  'drain': 'The runoff of water and nutrients from cannabis pots during feeding.',
  'dry': 'The initial drying phase after harvest where cannabis hangs to lose moisture.',
  'fan': 'A broad cannabis leaf or ventilation device used for airflow in grow rooms.',
  'feed': 'To provide water and nutrients to cannabis plants during their growth cycle.',
  'fem': 'Short for feminized seeds, bred to produce only female cannabis plants.',
  'fiber': 'The stalk material of hemp cannabis used for textiles, rope, and building.',
  'flora': 'The plant life of cannabis or the flowering stage of plant development.',
  'flower': 'The smokeable bud of the cannabis plant, or the blooming growth phase.',
  'flush': 'To water cannabis with pure water before harvest to remove residual nutrients.',
  'foliage': 'The collective leaves and greenery of a cannabis plant.',
  'frost': 'A thick, visible coating of trichomes on cannabis buds indicating high potency.',
  'germ': 'Short for germination, the process of sprouting cannabis seeds into seedlings.',
  'grow': 'To cultivate cannabis plants, or a cannabis cultivation facility.',
  'guard': 'A protective measure or leaf type that shields developing cannabis buds.',
  'harvest': 'The process of cutting down mature cannabis plants for drying and curing.',
  'herd': 'To manage and maintain a group of cannabis plants through their lifecycle.',
  'hybrid': 'A cannabis strain bred from both indica and sativa genetics for blended effects.',
  'indica': 'A cannabis subspecies known for relaxing body effects, shorter plants, and broad leaves.',
  'leaf': 'The flat, serrated foliage of a cannabis plant used for photosynthesis.',
  'lobe': 'One of the individual finger-like segments of a cannabis leaf blade.',
  'lumen': 'A unit measuring light output, important for optimizing cannabis grow light intensity.',
  'male': 'A cannabis plant that produces pollen sacs instead of smokeable flower buds.',
  'mother': 'A mature female cannabis plant kept in vegetative state for taking clones.',
  'mulch': 'A protective ground cover placed around cannabis plants to retain soil moisture.',
  'node': 'The point on a cannabis stem where branches and leaves emerge.',
  'nug': 'A single, trimmed piece of dried cannabis flower ready for consumption.',
  'nugs': 'Multiple pieces of trimmed, dried cannabis flower buds.',
  'nutrient': 'Essential minerals and compounds fed to cannabis plants for healthy growth.',
  'organic': 'Cannabis grown without synthetic pesticides or fertilizers using natural methods.',
  'peat': 'A spongy soil component used in cannabis growing mixes for water retention.',
  'pest': 'An unwanted insect or organism that damages cannabis plants during cultivation.',
  'pheno': 'Short for phenotype, a specific physical expression of a cannabis strain genetics.',
  'pistil': 'The hair-like reproductive organ on female cannabis flowers, often orange or red.',
  'plant': 'A cannabis organism cultivated for its cannabinoid and terpene-producing flowers.',
  'pollen': 'Fine powder from male cannabis plants used for breeding new strain varieties.',
  'pot': 'A container for growing cannabis plants, or classic slang for cannabis itself.',
  'prune': 'To trim excess leaves and branches from cannabis for better bud development.',
  'resin': 'The sticky, trichome-produced substance on cannabis rich in cannabinoids and terpenes.',
  'root': 'The underground structure of cannabis plants that absorbs water and nutrients.',
  'ruderalis': 'A small, wild cannabis subspecies that autoflowers regardless of light cycle.',
  'sap': 'The sticky fluid inside cannabis stems containing water, sugars, and nutrients.',
  'sativa': 'A cannabis subspecies known for tall growth, energizing effects, and cerebral highs.',
  'seed': 'The reproductive unit of cannabis used to start new plants from genetics.',
  'shake': 'Loose cannabis fragments and small pieces that collect at the bottom of containers.',
  'soil': 'The growing medium where cannabis roots develop and absorb nutrients.',
  'sprout': 'A newly germinated cannabis seedling emerging from its seed shell.',
  'stalk': 'The main structural stem of a cannabis plant supporting branches and buds.',
  'sticky': 'Describing resinous, trichome-rich cannabis that adheres to fingers when handled.',
  'strain': 'A specific genetic variety of cannabis with distinct effects, flavors, and appearance.',
  'tent': 'A reflective, enclosed growing space used for indoor cannabis cultivation.',
  'terra': 'Relating to earth or soil-based cannabis growing methods and mediums.',
  'top': 'To cut the main stem tip of cannabis to promote bushier lateral growth.',
  'tree': 'Slang for a large cannabis plant or general slang for marijuana.',
  'trellis': 'A net or frame supporting cannabis branches for even canopy light distribution.',
  'trichome': 'Tiny crystal glands on cannabis that produce cannabinoids, terpenes, and resin.',
  'trim': 'To remove excess leaves from cannabis buds after harvest for appearance and quality.',
  'veg': 'The vegetative growth stage before flowering when cannabis develops stems and leaves.',
  'vine': 'A trailing cannabis branch that extends and climbs when supported by trellising.',
  'water': 'The essential hydration supplied to cannabis plants throughout their growth cycle.',
  'wax': 'A soft, opaque cannabis concentrate with a waxy texture for dabbing.',
  'weed': 'The most common slang term for cannabis or marijuana.',
  'wet': 'Freshly harvested cannabis before drying, or improperly cured moist flower.',
  'yield': 'The total amount of dried cannabis flower harvested from a grow cycle.',

  // ── Industry & Dispensary Terms ──
  'bag': 'A packaging container for cannabis flower, often in pre-weighed quantities.',
  'bank': 'A seed bank that stores and sells cannabis genetics from various breeders.',
  'batch': 'A specific production lot of cannabis tracked from cultivation through sale.',
  'bid': 'An offer or price proposal in wholesale cannabis purchasing negotiations.',
  'bin': 'A storage container used for holding bulk cannabis in dispensary operations.',
  'brand': 'A licensed cannabis company producing products under a recognizable name and identity.',
  'bulk': 'Large-quantity cannabis purchases at wholesale pricing before individual packaging.',
  'buy': 'To purchase cannabis products from a licensed dispensary or retailer.',
  'cash': 'The primary payment method at many dispensaries due to banking restrictions.',
  'club': 'A cannabis social club or collective where members access products communally.',
  'coa': 'Certificate of Analysis, a lab report showing cannabinoid and contaminant test results.',
  'comply': 'To meet all regulatory requirements for legal cannabis operations and sales.',
  'cost': 'The price of cannabis products at wholesale or retail level.',
  'counter': 'The dispensary service area where budtenders assist customers with product selection.',
  'deal': 'A sale, promotion, or wholesale transaction involving cannabis products.',
  'delivery': 'A licensed service bringing cannabis products directly to customers at their location.',
  'dispo': 'Slang abbreviation for dispensary, a licensed retail cannabis store.',
  'dose': 'A measured amount of cannabis consumed, especially important for edibles and tinctures.',
  'drop': 'A new product release or a measured tincture dose administered under the tongue.',
  'eighth': 'One-eighth of an ounce (3.5 grams), the most common cannabis purchase size.',
  'extract': 'A cannabis concentrate produced by separating cannabinoids and terpenes from plant material.',
  'farm': 'A licensed cannabis cultivation operation growing plants for commercial production.',
  'fill': 'To load cannabis oil into vape cartridges or fill product inventory.',
  'firm': 'A cannabis business entity involved in production, distribution, or retail.',
  'gram': 'The base unit of weight for measuring and selling cannabis, about one joint.',
  'green': 'Slang for cannabis, or the color associated with cannabis culture and products.',
  'grind': 'To break cannabis flower into smaller pieces using a grinder for consumption.',
  'half': 'A half-ounce of cannabis (14 grams), a common bulk purchase quantity.',
  'hash': 'A concentrated cannabis product made by compressing trichomes and resin together.',
  'hub': 'A central distribution or retail location in a cannabis supply chain.',
  'label': 'Required product packaging information including strain, potency, ingredients, and warnings.',
  'lab': 'A testing facility that analyzes cannabis for potency, terpenes, and contaminants.',
  'legal': 'Cannabis products and operations compliant with state and local regulations.',
  'license': 'A government-issued permit authorizing cannabis cultivation, processing, or retail sales.',
  'lid': 'An old-school term for approximately one ounce of cannabis.',
  'lot': 'A specific tracked batch of cannabis product from seed through final sale.',
  'loud': 'Slang for extremely pungent, strong-smelling cannabis indicating high quality.',
  'market': 'The cannabis industry marketplace where products are bought and sold commercially.',
  'med': 'Short for medical cannabis, products used for therapeutic purposes with a card.',
  'menu': 'A dispensary product listing showing available strains, prices, and descriptions.',
  'micro': 'A small-scale licensed cannabis operation, or microdosing small amounts for subtle effects.',
  'ounce': 'A standard cannabis measurement equaling 28 grams, often the legal possession limit.',
  'pack': 'A pre-packaged quantity of cannabis products like pre-rolls or edibles.',
  'patron': 'A dispensary customer or regular visitor who purchases cannabis products.',
  'permit': 'Official authorization allowing cannabis business operations in a specific jurisdiction.',
  'pharm': 'A pharmaceutical-style cannabis operation focused on medical products and precision dosing.',
  'plug': 'Slang for a cannabis supplier or connection, or a product recommendation.',
  'potency': 'The strength of cannabis measured by cannabinoid percentage, especially THC content.',
  'preroll': 'A pre-made cannabis joint sold ready to smoke at dispensaries.',
  'price': 'The retail cost of cannabis products at a dispensary.',
  'product': 'Any cannabis item sold at a dispensary including flower, edibles, and concentrates.',
  'profit': 'Revenue remaining after costs in cannabis business operations.',
  'promo': 'A promotional deal or discount offered by dispensaries to attract customers.',
  'quad': 'A quarter-ounce of cannabis (7 grams), a common mid-range purchase quantity.',
  'quality': 'The overall grade of cannabis based on appearance, aroma, flavor, and effects.',
  'rec': 'Short for recreational cannabis, products sold to adults without a medical card.',
  'retail': 'The direct-to-consumer sale of cannabis products through licensed dispensaries.',
  'review': 'Customer feedback on cannabis strains and products shared online or in-store.',
  'safe': 'A secure storage unit for cannabis inventory and cash at dispensaries.',
  'sale': 'A discounted price event or individual cannabis product transaction.',
  'sell': 'To offer cannabis products for purchase through licensed retail channels.',
  'shelf': 'The display tier at a dispensary indicating product quality level.',
  'shop': 'A cannabis retail store or dispensary where customers browse and purchase.',
  'smoke': 'To inhale combusted cannabis, or slang referring to cannabis flower itself.',
  'stock': 'The available inventory of cannabis products at a dispensary.',
  'store': 'A licensed cannabis retail location where products are sold to consumers.',
  'supply': 'The available quantity of cannabis products from growers and distributors.',
  'tax': 'Government-imposed charges on cannabis sales, often including excise and sales taxes.',
  'terp': 'Short for terpene, the aromatic compound defining cannabis flavor and effects.',
  'test': 'Laboratory analysis of cannabis for potency, purity, and safety compliance.',
  'tier': 'A quality or pricing level used to categorize cannabis products on menus.',
  'tincture': 'A liquid cannabis extract in alcohol or oil taken sublingually under the tongue.',
  'topical': 'A cannabis-infused cream, balm, or lotion applied to the skin for localized relief.',
  'total': 'The combined cannabinoid content or final purchase amount of cannabis products.',
  'unit': 'A single countable cannabis product item tracked in dispensary inventory systems.',
  'upsell': 'Recommending additional or premium cannabis products to increase a customer transaction.',
  'vendor': 'A licensed cannabis supplier providing products to dispensaries for retail sale.',
  'vet': 'To verify the quality and legitimacy of cannabis products or business partners.',
  'wholesale': 'Bulk cannabis sales from producers to dispensaries at discounted commercial pricing.',
  'zip': 'Slang for one ounce (28 grams) of cannabis flower.',

  // ── Slang ──
  'bake': 'To get high on cannabis, or to prepare cannabis-infused edibles in an oven.',
  'baked': 'Slang for being very high on cannabis, especially with a spacey feeling.',
  'blast': 'To consume a large amount of cannabis quickly for an intense high.',
  'blaze': 'To smoke cannabis, or a general term for the act of getting high.',
  'blazed': 'Slang for being visibly and intensely high on cannabis.',
  'chief': 'To take excessively long or frequent hits from a shared cannabis session.',
  'chronic': 'Slang for high-quality cannabis, popularized by Dr. Dre in the 1990s.',
  'cloud': 'A thick exhale of cannabis vapor or smoke, or a brand aesthetic.',
  'cough': 'The reflex response to harsh cannabis smoke, often signaling a strong hit.',
  'crispy': 'Slang for being very high, or describing well-cured, properly dried cannabis.',
  'dank': 'Slang for high-quality, potent, aromatic cannabis with strong smell and effects.',
  'dazed': 'A disoriented, spacey mental state from consuming potent cannabis.',
  'dope': 'Classic slang for cannabis, or an adjective meaning excellent quality.',
  'faded': 'Slang for being high and relaxed, often with a dreamy, hazy sensation.',
  'fried': 'Slang for being extremely high with impaired cognitive function from cannabis.',
  'ganja': 'A term for cannabis originating from Hindi, commonly used in Jamaican culture.',
  'gone': 'Slang for being extremely high to the point of mental absence.',
  'goofy': 'A silly, laugh-prone state caused by giggly, euphoric cannabis strains.',
  'herb': 'A natural, plant-based term for cannabis flower used for consumption.',
  'hit': 'A single inhalation of cannabis smoke or vapor from any device.',
  'hot': 'Cannabis that exceeds legal THC limits, or a dispensary under regulatory scrutiny.',
  'jane': 'Short for Mary Jane, a classic slang nickname for cannabis.',
  'kind': 'Short for kind bud, referring to high-quality, seedless cannabis flower.',
  'legit': 'Slang for authentic, high-quality cannabis from a licensed, legal source.',
  'mary': 'Short for Mary Jane, one of the oldest slang names for cannabis.',
  'mids': 'Medium-quality cannabis that falls between top-shelf and low-grade flower.',
  'mist': 'A fine cannabis vapor or spray, or a strain with light, airy effects.',
  'phat': 'Slang for excellent, premium-quality cannabis with impressive appearance and effects.',
  'purp': 'Slang for purple-hued cannabis strains with grape-like colors and flavors.',
  'reefer': 'Classic slang for a cannabis joint or cannabis in general.',
  'rip': 'A hard, deep inhalation from a bong, pipe, or dab rig.',
  'roast': 'To smoke cannabis, or to completely combust a bowl of flower.',
  'sesh': 'Short for session, a social gathering centered around cannabis consumption.',
  'smoked': 'Past tense of smoking cannabis, or slang for being defeated or exhausted.',
  'snoop': 'A reference to Snoop Dogg, an iconic figure in cannabis culture.',
  'spliff': 'A joint rolled with a mixture of cannabis and tobacco.',
  'stash': 'A personal hidden supply or collection of cannabis and accessories.',
  'stick': 'Slang for a joint, or a stem found in lower-quality cannabis flower.',
  'stoner': 'A person who regularly consumes cannabis as part of their lifestyle.',
  'stink': 'The strong, pungent aroma of potent cannabis flower with loud terpenes.',
  'toker': 'A cannabis consumer, someone who regularly tokes or smokes cannabis.',
  'trees': 'Slang for cannabis flower or marijuana in general.',
  'whip': 'A tubing attachment on vaporizers, or to mix cannabis into edible preparations.',
  'zooted': 'Slang for being extremely high and intoxicated from cannabis consumption.',

  // ── Consumption Methods ──
  'bite': 'To eat a small portion of a cannabis edible for controlled dosing.',
  'blow': 'To exhale cannabis smoke, or slang for smoking cannabis.',
  'brew': 'To steep cannabis into tea, coffee, or other hot infused beverages.',
  'burn': 'To ignite and combust cannabis flower for smoking in a pipe or joint.',
  'chew': 'To consume cannabis through chewable edibles like gummies or infused gum.',
  'cook': 'To prepare cannabis-infused edibles by heating cannabutter or oil into food.',
  'decarb': 'To heat raw cannabis activating THC from its acid form for edible potency.',
  'distill': 'To refine cannabis extract into a pure, potent distillate oil through distillation.',
  'drip': 'To dispense cannabis tincture drops or describe resinous concentrate consistency.',
  'eat': 'To consume cannabis through edibles like gummies, brownies, or infused foods.',
  'exhale': 'To breathe out cannabis smoke or vapor after holding an inhalation.',
  'heat': 'To apply warmth for decarboxylation, dabbing, or vaporizing cannabis products.',
  'huff': 'To inhale cannabis vapor quickly, usually from a vaporizer or dab setup.',
  'infuse': 'To incorporate cannabis extract into food, drinks, or topical products.',
  'inhale': 'To breathe in cannabis smoke or vapor into the lungs for absorption.',
  'load': 'To pack cannabis flower into a bowl, vaporizer, or other consumption device.',
  'melt': 'To liquefy cannabis concentrate on a heated surface for dabbing inhalation.',
  'mix': 'To blend cannabis with other herbs, strains, or ingredients for consumption.',
  'parch': 'To dry-heat cannabis for light decarboxylation or toasting before use.',
  'pass': 'To hand a joint, blunt, or pipe to the next person in rotation.',
  'paste': 'A thick, tar-like cannabis concentrate or infused preparation for edibles.',
  'pull': 'To inhale or draw smoke through a pipe, bong, or joint.',
  'pump': 'To push air through a vaporizer or inflate cannabis consumption bags.',
'snap': 'To clear an entire bowl in one hit, pulling all flower through.',
  'steep': 'To soak cannabis in hot liquid for making infused tea or beverages.',
  'sub': 'Short for sublingual, placing tincture drops under the tongue for fast absorption.',
  'twist': 'To pinch and seal the end of a joint or blunt closed.',
  'zap': 'To quickly heat cannabis concentrate with an electronic device for instant vaporization.',
}
